# Generated by Django 3.0.3 on 2020-03-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_auto_20200306_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='identifier',
            field=models.IntegerField(verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.CharField(max_length=100, verbose_name='URL фотографии'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='person',
            name='parent_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Интификатор начальника'),
        ),
        migrations.AlterField(
            model_name='person',
            name='post',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность'),
        ),
    ]
