# Generated by Django 3.0.3 on 2020-03-12 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_personmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonManager',
        ),
    ]
