# Generated by Django 3.0.3 on 2020-03-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_auto_20200306_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='parent_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Идентификатор начальника'),
        ),
    ]
