# Generated by Django 3.0.3 on 2020-03-12 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_delete_personmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='chief',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person', to='tree.Person', verbose_name='Начальник'),
        ),
    ]
