# Generated by Django 3.0.3 on 2020-03-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0006_auto_20200315_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='number_subordinates_hr',
            field=models.IntegerField(default=0, verbose_name='Количество подчиненных высшего ранга'),
        ),
        migrations.AddField(
            model_name='person',
            name='total_number_subordinates',
            field=models.IntegerField(default=0, verbose_name='Общее количество подчиненных'),
        ),
    ]
