# Generated by Django 3.0.3 on 2020-03-19 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0007_auto_20200316_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='total_number_subordinates',
        ),
    ]
